server.port=8080

# Kafka Configuration
kafka.bootstrap-servers=localhost:9092
kafka.consumer.group-id=my-group
kafka.consumer.auto-offset-reset=earliest
kafka.topic.input=test_IN
kafka.topic.output=test_OUT

# Thread Pool Configuration
app.thread-pool.core-pool-size=5
app.thread-pool.max-pool-size=10
app.thread-pool.queue-capacity=100

# Logging configuration
logging.level.com.example.microservice=DEBUG
